#!/usr/bin/env bash
# script that will display information about subdomains.
show_subdomains()
{
	result=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:'| tail -1 | tr '\t' ' ')
	ip=$(echo "$result" | cut -d' ' -f5-)
	register=$(echo "$result" | cut -d' ' -f4)
	echo "$1 $register $ip" | awk '{ print "The subdomain "$1" is a "$2" record and points to " $3 }'
}
if [ "$#" == 1 ]
then
	show_subdomains "www" "$1"
	show_subdomains "lb-01" "$1"
	show_subdomains "web-01" "$1"
	show_subdomains "web-02" "$1"
fi
if [ "$#" == 2 ]
then
	show_subdomains "$2" "$1"
fi
