#!/usr/bin/env bash
#Installs nginx server and set an html file to show for GET requests
apt update
apt install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default << "EOF"
# Default server configuration
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
}
EOF

service nginx restart

