#!/usr/bin/env bash
# This script makes nginx server listen on port 8080
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
